# Generated by Django 3.0.5 on 2020-08-14 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('paid', models.FloatField()),
                ('dayCost', models.FloatField()),
                ('incubatorClean', models.FloatField()),
                ('consumable', models.FloatField()),
                ('analysis', models.FloatField()),
                ('xRay', models.FloatField()),
                ('lightRays', models.FloatField()),
                ('medicine', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Incubator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('startTime', models.IntegerField()),
                ('isStarTimePM', models.BooleanField()),
                ('endTime', models.IntegerField()),
                ('isEndTimePM', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('createdDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('dateOfBirth', models.DateTimeField()),
                ('createdDate', models.DateTimeField()),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='incubator.User')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('dateOfBirth', models.DateTimeField()),
                ('createdDate', models.DateTimeField()),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='incubator.User')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('motherName', models.CharField(max_length=100)),
                ('fatherName', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('dateOfBirth', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=500)),
                ('weight', models.FloatField()),
                ('ssn', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='incubator.User')),
                ('conditionId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patients', to='incubator.Condition')),
                ('incubatorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patients', to='incubator.Incubator')),
            ],
        ),
        migrations.CreateModel(
            name='BillExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('billId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billextra', to='incubator.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartRate', models.FloatField()),
                ('pulseRate', models.FloatField()),
                ('oxygen', models.FloatField()),
                ('weight', models.FloatField()),
                ('sugar', models.FloatField()),
                ('urine', models.FloatField()),
                ('stool', models.FloatField()),
                ('bloodPressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('incubatorTemperature', models.FloatField()),
                ('createdDate', models.DateTimeField()),
                ('nurseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='incubator.Nurse')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='incubator.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientXRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('createdDate', models.DateTimeField()),
                ('xRayId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xraypatient', to='incubator.XRay')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientxray', to='incubator.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientphone', to='incubator.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicineDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('createdDate', models.DateTimeField()),
                ('medicineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicinepatientdoctor', to='incubator.Medicine')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorpatientmedicine', to='incubator.Doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientmedicinedoctor', to='incubator.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientConsumableNurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('createdDate', models.DateTimeField()),
                ('consumableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumbalepatientnurse', to='incubator.Consumable')),
                ('nurseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursepatientconsumable', to='incubator.Nurse')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientconsumablenurse', to='incubator.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=200)),
                ('createdDate', models.DateTimeField()),
                ('analysisId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysispatient', to='incubator.Analysis')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientanalysis', to='incubator.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='NurseShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField()),
                ('isSignedIn', models.BooleanField()),
                ('endDateTime', models.DateTimeField()),
                ('isSignedOut', models.BooleanField()),
                ('createdDate', models.DateTimeField()),
                ('changedDate', models.DateTimeField()),
                ('shiftId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftnurse', to='incubator.Shift')),
                ('nurseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurseshift', to='incubator.Nurse')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField()),
                ('isSignedIn', models.BooleanField()),
                ('endDateTime', models.DateTimeField()),
                ('isSignedOut', models.BooleanField()),
                ('createdDate', models.DateTimeField()),
                ('changedDate', models.DateTimeField()),
                ('shiftId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftdoctor', to='incubator.Shift')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorshift', to='incubator.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='incubator.Patient'),
        ),
    ]
