# Generated by Django 3.0.5 on 2020-09-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmedicinedoctor',
            old_name='status',
            new_name='billStatus',
        ),
        migrations.AddField(
            model_name='patientanalysis',
            name='billStatus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientconsumablenurse',
            name='billStatus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientxray',
            name='billStatus',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
