# Generated by Django 3.0.5 on 2020-09-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLaboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=500)),
                ('billStatus', models.CharField(blank=True, max_length=50)),
                ('createdDate', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Analysis',
            new_name='Laboratory',
        ),
        migrations.DeleteModel(
            name='PatientAnalysis',
        ),
        migrations.AddField(
            model_name='patientlaboratory',
            name='laboratoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorypatient', to='incubator.Laboratory'),
        ),
        migrations.AddField(
            model_name='patientlaboratory',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientlaboratory', to='incubator.Patient'),
        ),
    ]
