# Generated by Django 3.0.5 on 2020-08-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorshift',
            name='isSignedIn',
            field=models.BooleanField(default=False),
        ),
    ]
