# Generated by Django 3.0.5 on 2020-08-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseshift',
            name='nurseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurseshift', to='incubator.Nurse'),
        ),
    ]
