# Generated by Django 3.0.5 on 2020-08-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicinedoctor',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
