# Generated by Django 3.0.5 on 2020-07-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='daycost',
            new_name='dayCost',
        ),
    ]
