# Generated by Django 3.0.5 on 2020-08-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='colorId',
        ),
        migrations.AddField(
            model_name='condition',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
