# Generated by Django 3.0.5 on 2020-10-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsumablenurse',
            name='billStatus',
        ),
        migrations.RemoveField(
            model_name='patientextra',
            name='billStatus',
        ),
        migrations.RemoveField(
            model_name='patientlaboratory',
            name='billStatus',
        ),
        migrations.RemoveField(
            model_name='patientmedicinedoctor',
            name='billStatus',
        ),
        migrations.RemoveField(
            model_name='patientxray',
            name='billStatus',
        ),
    ]
