# Generated by Django 3.0.5 on 2020-08-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('dateOfBirth', models.DateTimeField()),
                ('createdDate', models.DateTimeField()),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accoutantdetial', serialize=False, to='incubator.User')),
            ],
        ),
        migrations.DeleteModel(
            name='FrontDesk',
        ),
    ]
