# Generated by Django 3.0.5 on 2020-08-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_auto_20200803_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientphone',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPhone', to='incubator.Patient'),
        ),
    ]
