# Generated by Django 3.0.5 on 2020-08-01 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_auto_20200801_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billextra',
            name='billId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billextra', to='incubator.Bill'),
        ),
    ]
