# Generated by Django 3.0.5 on 2020-08-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_patientmedicinedoctor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicinedoctor',
            name='dateTimer',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientanalysis',
            name='result',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='patientmedicinedoctor',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='patientxray',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
