# Generated by Django 3.0.5 on 2020-09-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_auto_20200909_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='analysis',
            new_name='laboratory',
        ),
    ]
