# Generated by Django 3.0.5 on 2020-08-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_auto_20200805_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientanalysis',
            name='result',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
