# Generated by Django 3.0.5 on 2020-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_remove_patient_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
