# Generated by Django 3.0.5 on 2020-08-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0003_auto_20200806_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientxray',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
