# Generated by Django 3.0.5 on 2020-08-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0004_auto_20200806_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
