# Generated by Django 3.0.5 on 2020-08-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0004_auto_20200803_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
