# Generated by Django 3.0.5 on 2020-08-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0005_analysis_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
