# Generated by Django 3.0.5 on 2020-08-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0005_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='gender',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
