# Generated by Django 3.0.5 on 2020-08-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0006_nurse_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicinedoctor',
            name='createdDate',
            field=models.DateTimeField(),
        ),
    ]
