# Generated by Django 3.0.5 on 2020-08-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0007_auto_20200809_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientanalysis',
            name='createdDate',
            field=models.DateTimeField(),
        ),
    ]
