# Generated by Django 3.0.5 on 2020-08-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0008_auto_20200809_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsumablenurse',
            name='createdDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patientxray',
            name='createdDate',
            field=models.DateTimeField(),
        ),
    ]
