# Generated by Django 3.0.5 on 2020-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0009_auto_20200809_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='createdDate',
            field=models.DateTimeField(),
        ),
    ]
