# Generated by Django 3.0.5 on 2020-08-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0010_auto_20200809_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='startDate',
        ),
        migrations.AddField(
            model_name='shift',
            name='endTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='isEndTimePM',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='isStarTimePM',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='name',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='startTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
