import 'package:incubatorapp/main.dart';

class BasicData {
  void addIncubatorData() {
    incubatorModel.incubatorList.clear();
    for (int i = 1; i <= 10; i++) {
      incubatorModel.createIncubator();
      incubatorModel.setName(i.toString());
      incubatorModel.create();
    }
  }

  void addConditionData() {
    conditionModel.conditionList.clear();

    conditionModel.createCondition();
    conditionModel.setName('Normal');
    conditionModel.setPrice(300);
    conditionModel.create();

    conditionModel.createCondition();
    conditionModel.setName('Oxygen');
    conditionModel.setPrice(400);
    conditionModel.create();

    conditionModel.createCondition();
    conditionModel.setName('Artificial Breathing');
    conditionModel.setPrice(500);
    conditionModel.create();
  }

  void addShiftData() {
    shiftModel.shiftList.clear();

    shiftModel.createShift();
    shiftModel.setName('A');
    shiftModel.setStartTime(9);
    shiftModel.setIsStartTimePM(false);
    shiftModel.setEndTime(3);
    shiftModel.setIsEndTimePM(true);
    shiftModel.create();

    shiftModel.createShift();
    shiftModel.setName('B');
    shiftModel.setStartTime(3);
    shiftModel.setIsStartTimePM(true);
    shiftModel.setEndTime(9);
    shiftModel.setIsEndTimePM(true);
    shiftModel.create();

    shiftModel.createShift();
    shiftModel.setName('C');
    shiftModel.setStartTime(9);
    shiftModel.setIsStartTimePM(true);
    shiftModel.setEndTime(9);
    shiftModel.setIsEndTimePM(false);
    shiftModel.create();
  }

  void addLaboratoryData() {
    laboratoryModel.laboratoryList.clear();

    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Allergy Blood Test');
    laboratoryModel.setPrice(50);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Allergy Skin Test');
    laboratoryModel.setPrice(55);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Alpha Fetoprotein (AFP) Tumor Marker Test');
    laboratoryModel.setPrice(60);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Alpha-1 Antitrypsin Test');
    laboratoryModel.setPrice(50);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Alpha-Fetoprotein (AFP) Test');
    laboratoryModel.setPrice(65);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('ALT Blood Test');
    laboratoryModel.setPrice(70);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Bilirubin Blood Test');
    laboratoryModel.setPrice(50);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Bilirubin in Urine');
    laboratoryModel.setPrice(75);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Blood Alcohol Level');
    laboratoryModel.setPrice(80);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Blood Differential');
    laboratoryModel.setPrice(50);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Blood Glucose Test');
    laboratoryModel.setPrice(85);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Blood in Urine');
    laboratoryModel.setPrice(90);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Blood Oxygen Level');
    laboratoryModel.setPrice(50);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Chloride Blood Test');
    laboratoryModel.setPrice(95);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Cholesterol Levels');
    laboratoryModel.setPrice(100);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Coagulation Factor Tests');
    laboratoryModel.setPrice(50);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Cognitive Testing');
    laboratoryModel.setPrice(105);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Complement Blood Test');
    laboratoryModel.setPrice(110);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Complete Blood Count (CBC)');
    laboratoryModel.setPrice(50);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Glucose in Urine Test');
    laboratoryModel.setPrice(115);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Hemoglobin A1C (HbA1c) Test');
    laboratoryModel.setPrice(120);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Hemoglobin Electrophoresis');
    laboratoryModel.setPrice(50);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Hemoglobin Test');
    laboratoryModel.setPrice(125);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Hepatitis Panel');
    laboratoryModel.setPrice(130);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Immunoglobulins Blood Test');
    laboratoryModel.setPrice(50);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('Insulin in Blood');
    laboratoryModel.setPrice(135);
    laboratoryModel.create();
    laboratoryModel.createLaboratory();
    laboratoryModel.setName('White Blood Cell (WBC) in Stool');
    laboratoryModel.setPrice(140);
    laboratoryModel.create();
  }

  void addXRayData() {
    xRayModel.xRayList.clear();

    xRayModel.createXRay();
    xRayModel.setName(' Chest x-ray');
    xRayModel.setPrice(105);
    xRayModel.create();
    xRayModel.createXRay();
    xRayModel.setName('Abdominal x-ray');
    xRayModel.setPrice(110);
    xRayModel.create();
    xRayModel.createXRay();
    xRayModel.setName('Bone x-rays');
    xRayModel.setPrice(50);
    xRayModel.create();
    xRayModel.createXRay();
    xRayModel.setName('computed tomography (CT)');
    xRayModel.setPrice(115);
    xRayModel.create();
    xRayModel.createXRay();
    xRayModel.setName(' magnetic resonance imaging');
    xRayModel.setPrice(120);
    xRayModel.create();
    xRayModel.createXRay();
    xRayModel.setName('Upper gastrointestinal tract radiography');
    xRayModel.setPrice(50);
    xRayModel.create();
    xRayModel.createXRay();
    xRayModel.setName('Fluoroscopy');
    xRayModel.setPrice(125);
    xRayModel.create();
    xRayModel.createXRay();
    xRayModel.setName('Lower intestinal tract radiography');
    xRayModel.setPrice(130);
    xRayModel.create();
  }

  void addMedicineData() {
    medicineModel.medicineList.clear();

    medicineModel.createMedicine();
    medicineModel.setName('Unasyan');
    medicineModel.setAmount(10);
    medicineModel.setPrice(40);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Claforan');
    medicineModel.setAmount(10);
    medicineModel.setPrice(45);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Amikin');
    medicineModel.setAmount(10);
    medicineModel.setPrice(50);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Calcium');
    medicineModel.setAmount(10);
    medicineModel.setPrice(55);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Meronem');
    medicineModel.setAmount(10);
    medicineModel.setPrice(60);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Epidron');
    medicineModel.setAmount(10);
    medicineModel.setPrice(65);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Vanco');
    medicineModel.setAmount(10);
    medicineModel.setPrice(70);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Tienam');
    medicineModel.setAmount(10);
    medicineModel.setPrice(75);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Aminophylline');
    medicineModel.setAmount(10);
    medicineModel.setPrice(80);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Zantac');
    medicineModel.setAmount(10);
    medicineModel.setPrice(85);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Rocephin');
    medicineModel.setAmount(10);
    medicineModel.setPrice(90);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Lasix');
    medicineModel.setAmount(10);
    medicineModel.setPrice(95);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Flagyl');
    medicineModel.setAmount(10);
    medicineModel.setPrice(100);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Haemokion');
    medicineModel.setAmount(10);
    medicineModel.setPrice(105);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Maxipime');
    medicineModel.setAmount(10);
    medicineModel.setPrice(110);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Dobutrex');
    medicineModel.setAmount(10);
    medicineModel.setPrice(115);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Dpamine');
    medicineModel.setAmount(10);
    medicineModel.setPrice(120);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Potassium');
    medicineModel.setAmount(10);
    medicineModel.setPrice(125);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Magnesium');
    medicineModel.setAmount(10);
    medicineModel.setPrice(130);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Sominaletta');
    medicineModel.setAmount(10);
    medicineModel.setPrice(135);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Solu-Cortef');
    medicineModel.setAmount(10);
    medicineModel.setPrice(140);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Sodium bicarbonate');
    medicineModel.setAmount(10);
    medicineModel.setPrice(145);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Farcolin');
    medicineModel.setAmount(10);
    medicineModel.setPrice(150);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Bisolvon');
    medicineModel.setAmount(10);
    medicineModel.setPrice(155);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Atrovent');
    medicineModel.setAmount(10);
    medicineModel.setPrice(160);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Folic acid');
    medicineModel.setAmount(10);
    medicineModel.setPrice(165);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Capoten');
    medicineModel.setAmount(10);
    medicineModel.setPrice(170);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Adrenaline');
    medicineModel.setAmount(10);
    medicineModel.setPrice(175);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Atropine');
    medicineModel.setAmount(10);
    medicineModel.setPrice(180);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Epanuton');
    medicineModel.setAmount(10);
    medicineModel.setPrice(185);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Heparin');
    medicineModel.setAmount(10);
    medicineModel.setPrice(190);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Haemostop');
    medicineModel.setAmount(10);
    medicineModel.setPrice(195);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Fentanyl');
    medicineModel.setAmount(10);
    medicineModel.setPrice(200);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Konakion');
    medicineModel.setAmount(10);
    medicineModel.setPrice(205);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Phenytoin');
    medicineModel.setAmount(10);
    medicineModel.setPrice(210);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Pulmicort');
    medicineModel.setAmount(10);
    medicineModel.setPrice(215);
    medicineModel.create();
    medicineModel.createMedicine();
    medicineModel.setName('Dormicum');
    medicineModel.setAmount(10);
    medicineModel.setPrice(220);
    medicineModel.create();
  }

  void addConsumableData() {
    consumableModel.consumableList.clear();

    consumableModel.createConsumable();
    consumableModel.setName('Newment');
    consumableModel.setAmount(10);
    consumableModel.setPrice(70);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Salt solution');
    consumableModel.setAmount(10);
    consumableModel.setPrice(75);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Glucose 10%');
    consumableModel.setAmount(10);
    consumableModel.setPrice(80);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Glucose 5%');
    consumableModel.setAmount(10);
    consumableModel.setPrice(85);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Mannitol');
    consumableModel.setAmount(10);
    consumableModel.setPrice(90);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Ranger');
    consumableModel.setAmount(10);
    consumableModel.setPrice(95);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('cotton');
    consumableModel.setAmount(10);
    consumableModel.setPrice(100);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Blaster');
    consumableModel.setAmount(10);
    consumableModel.setPrice(105);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Estrelim');
    consumableModel.setAmount(10);
    consumableModel.setPrice(110);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('A catheter');
    consumableModel.setAmount(10);
    consumableModel.setPrice(115);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('scalpel');
    consumableModel.setAmount(10);
    consumableModel.setPrice(120);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Javanese dye');
    consumableModel.setAmount(10);
    consumableModel.setPrice(125);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Syringe 50 cm');
    consumableModel.setAmount(10);
    consumableModel.setPrice(130);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Syringe 10 cm');
    consumableModel.setAmount(10);
    consumableModel.setPrice(135);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Syringe 5 cm');
    consumableModel.setAmount(10);
    consumableModel.setPrice(140);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Syringe 3 cm');
    consumableModel.setAmount(10);
    consumableModel.setPrice(145);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Insulin syringe');
    consumableModel.setAmount(10);
    consumableModel.setPrice(150);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Intravenous device');
    consumableModel.setAmount(10);
    consumableModel.setPrice(155);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Himo Set');
    consumableModel.setAmount(10);
    consumableModel.setPrice(160);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Cello Set');
    consumableModel.setAmount(10);
    consumableModel.setPrice(165);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Triple link');
    consumableModel.setAmount(10);
    consumableModel.setPrice(170);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Cannula 24 m');
    consumableModel.setAmount(10);
    consumableModel.setPrice(175);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Cannula 22 m');
    consumableModel.setAmount(10);
    consumableModel.setPrice(180);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('The nisle link');
    consumableModel.setAmount(10);
    consumableModel.setPrice(185);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('NeoBlazer link');
    consumableModel.setAmount(10);
    consumableModel.setPrice(190);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Suction catheter');
    consumableModel.setAmount(10);
    consumableModel.setPrice(195);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Rail feed');
    consumableModel.setAmount(10);
    consumableModel.setPrice(200);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Laryngeal tube');
    consumableModel.setAmount(10);
    consumableModel.setPrice(205);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Thermometer');
    consumableModel.setAmount(10);
    consumableModel.setPrice(210);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Eyeglasses');
    consumableModel.setAmount(10);
    consumableModel.setPrice(215);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Sugar bar');
    consumableModel.setAmount(10);
    consumableModel.setPrice(220);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Gloves sterile');
    consumableModel.setAmount(10);
    consumableModel.setPrice(225);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Leather gloves');
    consumableModel.setAmount(10);
    consumableModel.setPrice(230);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Sterile gauze');
    consumableModel.setAmount(10);
    consumableModel.setPrice(235);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Gauze strap');
    consumableModel.setAmount(10);
    consumableModel.setPrice(240);
    consumableModel.create();
    consumableModel.createConsumable();
    consumableModel.setName('Fecryl 0/3');
    consumableModel.setAmount(10);
    consumableModel.setPrice(245);
    consumableModel.create();
  }

  void addExtraData() {
    extraModel.extraList.clear();

    extraModel.createExtra();
    extraModel.setName('Incubator Clean');
    extraModel.setPrice(200);
    extraModel.create();

    extraModel.createExtra();
    extraModel.setName('Consultant');
    extraModel.setPrice(400);
    extraModel.create();

    extraModel.createExtra();
    extraModel.setName('Milk');
    extraModel.setPrice(100);
    extraModel.create();
  }

  void addStateTypeData() {
    stateTypeModel.stateTypeList.clear();

    stateTypeModel.createStateType();
    stateTypeModel.setName('In');
    stateTypeModel.create();

    stateTypeModel.createStateType();
    stateTypeModel.setName('Out');
    stateTypeModel.create();

    stateTypeModel.createStateType();
    stateTypeModel.setName('Passed a way');
    stateTypeModel.create();

    stateTypeModel.createStateType();
    stateTypeModel.setName('Transfer');
    stateTypeModel.create();
  }
}
