import 'package:incubatorapp/main.dart';
import 'package:incubatorapp/models/userpermission.dart';
import 'package:incubatorapp/scopedmodels/usermodel.dart';

class UserData {
  void addUserPatientData() {
    userModel.createUser();
    userModel.setUserType(UserType.patient);
    userModel.setEmail('mahmoud@gmail.com');
    userModel.setPassword('mahmoud@1999');
    userModel.setProvider(UserProvider.other);
    userModel.setPhone('+0201019340608');
    userModel.create();
    userModel.createUser();
    userModel.setUserType(UserType.patient);
    userModel.setEmail('ibrahim@gmail.com');
    userModel.setPassword('ibrahim@2000');
    userModel.setProvider(UserProvider.other);
    userModel.setPhone('+0201019340608');
    userModel.create();
    userModel.createUser();
    userModel.setUserType(UserType.patient);
    userModel.setEmail('yasser@gmail.com');
    userModel.setPassword('yasser@2001');
    userModel.setProvider(UserProvider.other);
    userModel.setPhone('+0201019340608');
    userModel.create();
    userModel.createUser();
    userModel.setUserType(UserType.patient);
    userModel.setEmail('adel@gmail.com');
    userModel.setPassword('adel@2002');
    userModel.setProvider(UserProvider.other);
    userModel.setPhone('+0201019340608');
    userModel.create();
    userModel.createUser();
    userModel.setUserType(UserType.patient);
    userModel.setEmail('nermen@gmail.com');
    userModel.setPassword('nermen@2003');
    userModel.setProvider(UserProvider.other);
    userModel.setPhone('+0201019340608');
    userModel.create();
    userModel.createUser();
    userModel.setUserType(UserType.patient);
    userModel.setEmail('yasmin@gmail.com');
    userModel.setPassword('yasmin@2004');
    userModel.setProvider(UserProvider.other);
    userModel.setPhone('+0201019340608');
    userModel.create();
    userModel.createUser();
    userModel.setUserType(UserType.patient);
    userModel.setEmail('mina@gmail.com');
    userModel.setPassword('mina@2005');
    userModel.setProvider(UserProvider.other);
    userModel.setPhone('+0201019340608');
    userModel.create();
    userModel.createUser();
    userModel.setUserType(UserType.patient);
    userModel.setEmail('rana@gmail.com');
    userModel.setPassword('rana@2006');
    userModel.setProvider(UserProvider.other);
    userModel.setPhone('+0201019340608');
    userModel.create();
    userModel.createUser();
    userModel.setUserType(UserType.patient);
    userModel.setEmail('sara@gmail.com');
    userModel.setPassword('sara@2007');
    userModel.setProvider(UserProvider.other);
    userModel.setPhone('+0201019340608');
    userModel.create();
  }

}
